apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
  namespace: covid19-ng
  labels:
    app: worker
spec:
  selector:
    matchLabels:
      app: worker
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - image: seyio/scraper-worker
          name: worker
          env:
            - name: REDIS_HOST
              value: ngcovid-cache
            - name: REDIS_PORT
              value: "6379"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: dburlpass
